name: Cygwin Build

on:
  pull_request:
    branches:
      - 1.2.x
  push:
    branches:
      - 1.2.x
      - develop-1.2.x
      - ci/cygwin-1.2.x
  workflow_dispatch:

jobs:
  cygwin:
    name: Cygwin x86_64
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: C:\cygwin64\bin\bash.exe -eo pipefail '{0}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cygwin packages
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile C:\cygwin-setup.exe
          C:\cygwin-setup.exe --quiet-mode --root C:\cygwin64 --site https://mirrors.kernel.org/sourceware/cygwin/ --packages autoconf,automake,dos2unix,gcc-core,gzip,help2man,inetutils,libmariadb-devel,libssl-devel,libtool,m4,make,net-snmp-devel,openssl-devel,pkg-config,wget

      - name: Bootstrap
        run: |
          export PATH=/usr/bin:$PATH
          ./bootstrap

      - name: Configure
        run: |
          export PATH=/usr/bin:$PATH
          ./configure --with-mysql=/usr --with-snmp=/usr

      - name: Build
        run: |
          export PATH=/usr/bin:$PATH
          make -j2 V=1
